{...}: {
  homebrew.casks = [
    "atv-remote"
    "discord"
    "docker-desktop"
    "gimp"
    "handbrake-app"
    "imageoptim"
    "latest"
    "macfuse"
    "microsoft-auto-update"
    "microsoft-teams"
    "openvpn-connect"
    "steam"
    "visual-studio-code"
    #"altair-graphql-client"
    #"balenaetcher"
    #"diffusionbee"
    #"mediathekview"
    #"mqttx"
    #"pgadmin4"
    #"raspberry-pi-imager"
    #"realvnc-connect-viewer"
    #"scribus"
    #"upscayl"
  ];
}
